
test_name: "dev"

num_agents: 4
target_position: 4
start_poses: "random"

architecture: "TD3"
window_in: 2
window_out: 1

map_mode: "Std"

n: 2
set_n: 1

random_seed: 10000
noise_std: 0.0

n_train_steps: 10000
n_test_laps: 20

map_name: "f1_esp"
reward: "Cth"

max_speed: 5

lr: 0.001
gamma: 0.001
context_info: [0.0, 0.0, 0.0, 0.0]


runs:
  - adversaries: ['PP', 'PP', 'PP']
  # - adversaries: ['DispExt', 'DispExt']






